### ISSUE TITLE
Add Readme Documentation

### ISSUE THREAD

**Issue by ratnakar5938** [ratnakar5938/React-Chat-App#1]
**Sections to add** - 

- [ ] Logo
- [x] Description
- [x] Package Needed
- [x] Contribution procedure
- [x] Tech Stack
- [x] Contributors section

**Description** - 
Chat App made in React

**Tech Stack** - 
- React
- React-Chat-Engine

**Deployment** - 
- Netlify

**Package Manager** - 
- Yarn

**Comment by namangirdhar16** [comment]
@ratnakar5938  i would like to work on this.

**Comment by ratnakar5938** [comment]
I will provide the links for the demo and screenshot tomorrow so u can start working

**Comment by ratnakar5938** [comment]
@namangirdhar16 
**Resources** - 

[demo gif](https://github.com/ratnakar5938/React-Chat-App/blob/master/demo.gif)

[💻HomePage](https://res.cloudinary.com/ratnakar5938/image/upload/v1635533156/React-chat%20app/Screenshot_147_cud1fx.png)
[📃Chats](https://res.cloudinary.com/ratnakar5938/image/upload/v1635533153/React-chat%20app/Screenshot_148_zrliyn.png)

**Comment by ratnakar5938** [comment]
Leave the contributions section as all-contributors bot will do that

**Comment by namangirdhar16** [comment]
@ratnakar5938 cool. I'm working on this.

**Comment by namangirdhar16** [comment]
@ratnakar5938 is this inclueded in hacktoberfest?

**Comment by ratnakar5938** [comment]
> @ratnakar5938 is this inclueded in hacktoberfest?

yes bt u need to do it fast as it ends tommorow

**Comment by namangirdhar16** [comment]
I will do it by today, just add hacktoberfest label to this issue, i'm left with 2 PRs if you know more beginner friendly projects do let me know.

**Comment by ratnakar5938** [comment]
> I will do it by today, just add hacktoberfest label to this issue, i'm left with 2 PRs if you know more beginner friendly projects do let me know.

I have other readme issues which you can add to

**Comment by ratnakar5938** [comment]
https://github.com/ratnakar5938/my-portfolio/issues/1
Can work on this
